name: "Build bazel on all systems"
on:
  push:
  workflow_dispatch:
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        os: [Linux, macOS]
        arch: [nixos, X64, ARM64]
        exclude:
          - os: Linux
            arch: X64
          - os: Linux
            arch: ARM64
          - os: macOS
            arch: nixos
          - os: macOS
            arch: X64
    #env:
    #  PATH: /run/wrappers/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin
    timeout-minutes: 20
    runs-on: ["${{ matrix.os }}", "${{ matrix.arch }}"]
    steps:
    - uses: actions/checkout@v4

    - name: Change maven.org to local nexus
      run: |
        for file in `find . \( -name "*WORKSPACE" -or -name "*.yaml" -or -name "*.bzl" -or -name "*.nix" -or -name "*.scala" \) -print`
          do
            export strFileNameFSproj=$file
            echo $strFileNameFSproj
            # Macos sed have'nt -i parameter so write to other file and rename it
            sed "s|https://repo1.maven.org/maven2|https://nexus.tawasal.ae/repository/maven-central|g"  $strFileNameFSproj > $strFileNameFSproj.new
            mv -f $strFileNameFSproj.new $strFileNameFSproj
            sed "s|https://repo.maven.apache.org/maven2|https://nexus.tawasal.ae/repository/maven-apache|g"  $strFileNameFSproj > $strFileNameFSproj.new
            mv -f $strFileNameFSproj.new $strFileNameFSproj
          done
    - name: Build nix flake
      env:
        LD_LIBRARY_PATH: ''
      run: nix build -L

    - name: Create files for store
      env:
        LD_LIBRARY_PATH: ''
        STORE_PRIVATE_KEY: ${{ secrets.STORE_KEY }}
      run: |
        mkdir ${{ github.workspace }}/.secrets
        echo "$STORE_PRIVATE_KEY" > ${{ github.workspace }}/.secrets/store_key
        rm -rf tostore
        mkdir -p tostore
        mkdir -p tostore/nar
        ls -d result*
        for i in `ls -d result*`
        do
          echo "Working with $i"
          nix store sign --key-file ${{ github.workspace }}/.secrets/store_key ./$i
          nix copy --to file://${{ github.workspace }}/tostore?compression=zstd ./$i
        done

    - name: Prepare secrets
      env:
        PRIVATE_KEY: ${{ secrets.SSH_KEY }}
      run: |
        echo "$PRIVATE_KEY" > ${{ github.workspace }}/.secrets/ssh_key
        chmod 0600 ${{ github.workspace }}/.secrets/ssh_key
        chmod 0700 ${{ github.workspace }}/.secrets
    - name: Copy to nix-store
      run: |
        cd tostore
        rsync -av \
          -e 'ssh -p ${{ vars.NIX_STORE_PORT }} -i ${{ github.workspace }}/.secrets/ssh_key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no' \
          * \
          teamcity@${{ vars.NIX_STORE_IP }}:/opt/nix-store/store
  
    - name: Clean
      if: ${{ always() }}
      run: |
        rm -rf ${{ github.workspace }}/.secrets
        rm -rf tostore
